apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jamespacheco-dev-tls
  namespace: default
spec:
  secretName: jamespacheco-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - jamespacheco.dev
  - "*.jamespacheco.dev"